### ISSUE TITLE
feat: Share intermediate representation of common sources among samplers

### ISSUE THREAD

**Issue by thinkingfish** [iopsystems/rezolus#11]
Some samplers may consume the same raw input, eg. `/proc/meminfo` that can also be a bit expensive to poll at high frequencies, we can design an general intermediate in-memory representation of the information from such sources so that samplers can query such internal representation instead of the raw source to but cut down overhead and reduce redundant parsing.

**Comment by brayniac** [comment]
I'm going to close this one out. I think this is a good strategy, but we'll incorporate it as we find the need for it. For now, we don't have the overlap that would demand this.
