### ISSUE TITLE
Filesystem occupancy metrics

### ISSUE THREAD

**Issue by brayniac** [iopsystems/rezolus#133]
We've received a request to add disk usage metrics to Rezolus, particularly free space on filesystems. This issue is to track adding that

**Comment by bxffour** [comment]
Hi there,

I'm Nana, and I'm interested in contributing to this issue. Before starting, I'd like to understand the expected output format and requirements for these metrics.

Could you please provide more details about what you're looking for in terms of the metrics representation?

Thanks!

**Comment by brayniac** [comment]
Hi @bxffour - thank you for your interest in contributing. This issue probably could've used a little more detail and I think I probably shouldn't have used the word 'utilization' in the issue description. What was wanted here was actually metrics around free space on filesystems. I've adjusted this issue to hopefully clarify the original intent.

Since that request for support, I've been giving more thought to where Rezolus provides value compared to other telemetry agents. I think the short answer there is that the value comes from low overhead collection of utilization and performance metrics. I feel like this request was more about health metrics, which I feel other projects tend to cover pretty well. 

With that framing in mind, I'm not sure this particular issue should remain open. I think efforts would be better spent in building out features which differentiate Rezolus from other telemetry agents and provide unique value.

If you'd like to chat more about ideas for the project and areas to contribute, feel free to join our discord (linked in the readme) and ping me to discuss.

**Comment by brayniac** [comment]
Closing this one out for now. Willing to revisit if there's sufficient demand.
