### ISSUE TITLE
bug: Panic when CPU hardware events are not available

### ISSUE THREAD

**Issue by l2dy** [iopsystems/rezolus#14]
Program panics when hardware perf_event is not available.

### Expected behavior

1. CPI sampler can be disabled from config, or
2. Disable the sampler if perf_event is not available.

### Actual behavior

Program panics at `expect()`.

https://github.com/iopsystems/rezolus/blob/8634df2e2a3ea83c14fc990a101de333af56ea22/src/samplers/cpu/cpi/mod.rs#L32

### Steps to reproduce the behavior

1. Run rezolus on Azure Linux VMs.

**Comment by brayniac** [comment]
Fixed in #16. Thanks for reporting this.
