### ISSUE TITLE
Wrong unit for metrics in `meminfo`

### ISSUE THREAD

**Issue by thinkingfish** [iopsystems/rezolus#220]
Unit of metrics in `/proc/sys/meminfo` is KiB, but currently [the metadata](https://github.com/iopsystems/rezolus/blob/3cf0f986e1b1717384c49114dc7440660792ecb4/src/samplers/memory/stats.rs#L7) in this module shows the unit as "bytes" which is incorrect.

**Comment by brayniac** [comment]
Fixed by #222
