### ISSUE TITLE
Port memcached sampler from Rezolus 2.x

### ISSUE THREAD

**Issue by thinkingfish** [iopsystems/rezolus#58]
We could use a Memcached sampler to get the service-level metrics into Rezolus and subsequent metrics exposition pipeline.

### Expected behavior

Request and format metrics from Memcached server.

### Actual behavior

This sampler was dropped during the rewrite that became Rezolus 5.x

### Approach

Will refer to and rewrite the previous implementation to make sure it complies with the new architecture and sampler template.

**Comment by brayniac** [comment]
Same with #57 

I think this should be closed as 'wontfix'. Since Rezolus has moved to on-demand sampling, I don't think it provides any benefit in acting as a proxy for service metrics. We would be better served by having a recording tool that produces a metric artifact directly.
